### ISSUE TITLE
big bro

### ISSUE THREAD

**Issue by huangqianhong** [Zhsc92157/SNESIM#2]
I want the code of the SNESIM with java version from you

**Comment by Zhsc92157** [comment]
I’m sorry to tell you that I found MPSLIB during the SNESIM encoding.


Therefore, the code is incomplete and I hope the MPSLIB with C++ version can help you (https://github.com/ergosimulation/mpslib).



Cui,Zhesi
China University of Geosciences,China
Tel:+86 13343413510


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhsc92157/SNESIM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 晚上8:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Zhsc92157/SNESIM] big bro (#2)





 
I want the code of the SNESIM with java version from you
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
